import Main from "@/components/layout/main";
import AppControls from "@/controls/app-controls";
import Footer from "@/features/navigation/footer";
import Navbar from "@/features/navigation/navbar";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/dist/client/components/navigation";
import { Neonderthaw, Raleway, Tilt_Neon } from "next/font/google";
import "./globals.css";

const neon = Tilt_Neon({ subsets: ["latin"], variable: "--font-neon" });

const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });
const neonderthaw = Neonderthaw({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-neonderthaw",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    // Enable static rendering
    setRequestLocale(locale);

    return (
        <html lang={locale} className="overflow-x-hidden">
            <body
                className={`${raleway.variable} ${neon.variable} ${neonderthaw.variable} antialiased`}
            >
                <AppControls>
                    <Navbar />
                    <Main>{children}</Main>
                    <Footer />
                </AppControls>
            </body>
        </html>
    );
}
